### PR TITLE
Hw3

### PR DESCRIPTION
**Pull request by Alvin-PDX**

### CODE REVIEW

**Comment by JeremiahTilse** [comment]
I don't have much to say on this.  Looks good.  

You could add some comments to show intention, or possibly put some of the if/else statements for checking cookies into blocks to clear up some of the flow, but not really needed.

For the form, I suggest a menu, for the "index" page.  Otherwise great.

Great work!

**Review by C3ra906 — COMMENTED** [review]
01: Nice job, everything is working great. 
02: I love how simple and affective your code is. I really had a hard time with this one and mine is way more complicated than yours. Great job!
03: So this one had conflicting instructions between the written description of the assignment and the screenshot she provided. Looks like you followed the written description and did a great job. Very nice and easy to understand. Great job again : )

**Comment by mattadlerpdx** [comment]
01: everything looks good. naming conventions are logical and your program is easy to read.
02: As others have stated, the flow of your program is awesome. Super intuitive names. 
03: Your code is simple to understand. It doesn't necessarily get into edge cases, ie. what happens when a form is submitted with a route besides form/submit. But that is what makes the code so easy to read and you followed instructions to the tee.

**Comment by JeremyIV** [comment]
ex1 and 2: Looks good to me.
Ex3: You're supposed to provide a few more input fields than this: a "comments" textarea and a "newsletter" checkbox.  You're missing these two. Also, I wouldn't recommend manually parsing the post request like this. There are packages that will make this easier, so you don't have to worry about, e.g. the `@` symbol showing up incorrectly. Otherwise, looks good, nice job!

**Pull request merged**
